server:
  port: 9090

spring:
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/DBMusteriHN
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update